<%@ Page Language="C#" AutoEventWireup="true" MasterPageFile="~/Admin.Master" CodeBehind="OfferCourse.aspx.cs" Inherits="Apollo.OfferCourse" %>
<asp:Content ContentPlaceHolderID="Admins" runat="server">
    <div class="section-body">
   <h2 class="section-title">Offer Course</h2>     
    <div class="row">
      <div class="col-12">
        <div class="card">
          <div class="card-header">
            <h4>Courses Details</h4>
              
              <div style="padding-left:650px">
                  <asp:Button ID="import" Text="IMPORT" CssClass="btn btn-primary" runat="server"/>
              </div>
           </div>
            <div class="card-body">
                <div class="form-group row mb-4">
                        <div class="table-responsive">
                           <asp:GridView ID="corelist" CssClass="table table-striped v_center" OnRowEditing="corelist_RowEditing" OnRowDeleting="corelist_RowDeleting"  runat="server" OnSelectedIndexChanged="corelist_SelectedIndexChanged" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AutoGenerateSelectButton="True"></asp:GridView>
                         </div>
                  </div>
            </div>
            <div class="card-header">
                <h5>
                    Selected Courses
                </h5>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <asp:GridView ID="selectedlist" CssClass="table table-striped v_center" runat="server" OnRowEditing="selectedlist_RowEditing"></asp:GridView>
                </div>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table">
                        <tr>
                            <td>
                                <asp:Button ID="newCourse" Text="Add New Course" CssClass="btn btn-primary btn-lg btn-block" runat="server" OnClick="newCourse_Click" />
                            </td>
                            <td>
                                <asp:Button ID="OfferCour" Text="Offer Course" CssClass="btn btn-primary btn-lg btn-block" runat="server" OnClick="OfferCour_Click" />
                            </td>
                        </tr>
                    </table>
                 </div>
            </div>
          </div>
         </div>
        </div>
     </div>
</asp:Content>
